sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck:stable

script:
  - docker run -v $(pwd):/scripts koalaman/shellcheck:stable /scripts/base16-manager

matrix:
  fast_finish: true
